"""Export the ISL MLP model + scaler to public/js/isl-model-data.js.

The browser loads this file so sign recognition can run entirely client-side
(in inference_server.py the exact same math runs server-side). Exporting the
raw weights keeps both paths bit-for-bit comparable — see the parity test in
/tmp/opencode/parity_test.py + parity_test.mjs.

Run:  python3 export_isl_model.py
"""

import json
import os
import pickle

ROOT = os.path.dirname(os.path.abspath(__file__))
MODELS = os.path.join(ROOT, "models")
OUT = os.path.join(ROOT, "public", "js", "isl-model-data.js")

SIG = "%.9g"


def g(v):
    """9 significant digits — plenty for float32-level output parity."""
    return float(SIG % float(v))


def main():
    with open(os.path.join(MODELS, "isl_mlp_model.pkl"), "rb") as f:
        clf = pickle.load(f)
    with open(os.path.join(MODELS, "isl_scaler.pkl"), "rb") as f:
        scaler = pickle.load(f)
    with open(os.path.join(MODELS, "isl_label_encoder.pkl"), "rb") as f:
        le = pickle.load(f)
    with open(os.path.join(MODELS, "isl_feature_config.pkl"), "rb") as f:
        cfg = pickle.load(f)

    layers = []
    for w, b in zip(clf.coefs_, clf.intercepts_):
        layers.append({
            "dim": [int(w.shape[0]), int(w.shape[1])],
            # stored column-major per output unit is awkward for JSON;
            # keep sklearn's (in, out) row-major layout and transpose in JS.
            "w": [g(v) for v in w.ravel().tolist()],
            "b": [g(v) for v in b.ravel().tolist()],
        })

    data = {
        "pipelineVersion": int(cfg.get("version", 1)) if isinstance(cfg, dict) else 1,
        "labels": [str(c) for c in le.classes_],
        "dims": [int(x) for x in [136, 256, 128, 64, 42]],
        "scaler": {
            "mean": [g(v) for v in scaler.mean_.ravel().tolist()],
            "scale": [g(v) for v in scaler.scale_.ravel().tolist()],
        },
        "layers": layers,
        "activation": getattr(clf, "activation", "relu"),
        "outActivation": getattr(clf, "out_activation_", "softmax"),
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Auto-generated by export_isl_model.py — do not edit by hand.\n")
        f.write("window.__ISL_MODEL__ = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")

    size = os.path.getsize(OUT)
    print(f"Wrote {OUT} ({size} bytes, {len(data['labels'])} classes, "
          f"layers {data['dims']})")


if __name__ == "__main__":
    main()
